steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-us-east1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-us-east1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA']

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'hello-world-python', 
           '--image=us-east1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA', 
           '--region', 'us-east1', '--platform', 'managed', 
           '--allow-unauthenticated']
options:
    logging: CLOUD_LOGGING_ONLY

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA

